In [1]:
import numpy as np
import pandas as pd
import scipy
from scipy import stats
from collections import Counter
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import norm, t
from scipy.stats import expon
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot,show,title ,xlabel,ylabel
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)



from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler

In [2]:
a = pd.read_csv(r"C:\Users\yzope\Downloads\payment_history.csv")
b = pd.read_csv(r"C:\Users\yzope\Downloads\monthly_emi_track.csv")
c = pd.read_csv(r"C:\Users\yzope\Downloads\loans_master.csv")
d = pd.read_csv(r"C:\Users\yzope\Downloads\loan_performance.csv")
e = pd.read_csv(r"C:\Users\yzope\Downloads\collateral_assets.csv")
f = pd.read_csv(r"C:\Users\yzope\Downloads\loan_enquiry_bureau.csv")
g = pd.read_csv(r"C:\Users\yzope\Downloads\customer_bureau.csv")
h = pd.read_csv(r"C:\Users\yzope\Downloads\credit_card_behavior.csv")
i = pd.read_csv(r"C:\Users\yzope\Downloads\branch_region_economy.csv")

In [3]:
a.head()

,loan_id,loan_status,lgd_pct,total_pymnt_inr,total_pymnt_inv_inr,total_rec_prncp_inr,total_rec_int_inr,last_pymnt_amnt_inr,out_prncp_inr,out_prncp_inv_inr,collection_recovery_fee,collections_12mths_fee,mths_since_last_pymnt,num_accts_ever_120_pd,num_derog_rec,acc_now_delinq,chargeoff_within_12_mths,expected_loss_inr
0,LN000000001,0,0.0,102327.83,98339.43,80678.0,21649.83,13922.84,0.0,0.0,0.0,0.0,1,0,0,0,0.0,0.0
1,LN000000002,0,0.0,319635.13,309461.58,274166.0,45469.13,22957.63,0.0,0.0,0.0,0.0,1,0,1,0,0.0,0.0
2,LN000000003,0,0.0,79687.39,78661.62,59603.0,20084.39,NaN,0.0,0.0,0.0,0.0,1,0,0,0,0.0,0.0
3,LN000000004,0,0.0,509995.37,492937.00,246313.0,263682.37,13529.63,0.0,0.0,0.0,0.0,2,0,0,0,0.0,0.0
4,LN000000005,0,0.0,126155.61,126048.04,101471.0,24684.61,9962.35,0.0,0.0,0.0,0.0,2,0,0,0,0.0,0.0

In [4]:
b.head()

,loan_id,installment_due_inr,total_emi_due_inr,total_emi_paid_inr,emi_overdue_inr,emi_bounce_count,consecutive_missed_emis,last_emi_payment_date,emi_advance_paid_inr,prepayment_flag,avg_payment_delay_days,payment_mode,emi_bank_name,penal_charges_inr,waiver_granted_flag,waiver_amount_inr,loan_restructured_flag,ots_offered_flag,ots_accepted_flag,emi_coverage_ratio,pdc_count,emi_to_income_ratio,payment_discipline
0,LN000000001,2793.17,100554.12,103925.57,0.00,0,0,Oct-2019,0.0,0,0.0,UPI,Union,0.00,0,0.0,0,0,0,3.99,6.0,0.2504,Excellent
1,LN000000002,8465.45,304756.20,308223.00,0.00,1,0,May-2024,0.0,0,5.0,NACH,SBI,1488.08,0,0.0,0,0,0,8.95,6.0,0.1117,Good
2,LN000000003,1366.55,81993.00,83657.21,0.00,1,0,Sep-2022,0.0,0,0.0,UPI,SBI,932.45,0,0.0,0,0,0,8.54,3.0,0.1171,Good
3,LN000000004,6088.88,511465.92,496707.66,14758.26,1,0,Jan-2023,0.0,0,0.0,Net Banking,ICICI,807.41,0,0.0,0,0,0,3.64,2.0,0.2750,Good
4,LN000000005,2082.81,124968.60,120842.83,4125.77,0,0,May-2017,0.0,0,0.0,Net Banking,ICICI,0.00,0,0.0,0,0,0,61.18,2.0,0.0163,Excellent

In [5]:
c.head()

,loan_id,issue_date,issue_year,issue_month,loan_amnt_inr,funded_amnt_inr,loan_term_months,int_rate_pct,installment_inr,annual_installment_inr,grade,sub_grade,loan_purpose,state_code,region,urban_index,application_type,pymnt_plan,hardship_flag,initial_list_status,disbursement_method,verification_status,rbi_repo_rate_pct,gdp_growth_pct,cpi_inflation_pct,rate_spread_pct,real_interest_rate_pct
0,LN000000001,Feb-2016,2016,2,80678.0,74992.0,36,14.91,2793.17,33518.0,C,C5,education,OR,East,0.33,Individual,N,N,w,DIRECT_PAY,Source Verified,6.25,8.2,4.5,8.66,10.41
1,LN000000002,May-2024,2024,5,274166.0,265041.0,36,7.00,8465.45,101585.0,A,A5,small_business,JH,East,0.36,Individual,N,N,w,CASH,Verified,6.50,6.8,4.9,0.50,2.10
2,LN000000003,Dec-2021,2021,12,59603.0,54423.0,60,13.34,1366.55,16399.0,D,D5,home_improvement,TN,South,0.72,Individual,N,N,w,DIRECT_PAY,Source Verified,4.00,8.7,5.1,9.34,8.24
3,LN000000004,Nov-2020,2020,11,246313.0,224181.0,84,24.07,6088.88,73067.0,G,G5,home_improvement,RJ,North,0.45,Joint App,N,N,w,DIRECT_PAY,Source Verified,4.00,-6.6,6.2,20.07,17.87
4,LN000000005,Jul-2013,2013,7,101471.0,95361.0,60,8.52,2082.81,24994.0,A,A5,vacation,DL,North,0.97,Individual,Y,N,w,CASH,Verified,7.75,6.4,10.9,0.77,-2.38

In [6]:
#here the dtypes are in float64
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 18 columns):
 #   Column                    Dtype
---  ------                    -----
 0   loan_id                   object
 1   loan_status               int64
 2   lgd_pct                   float64
 3   total_pymnt_inr           float64
 4   total_pymnt_inv_inr       float64
 5   total_rec_prncp_inr       float64
 6   total_rec_int_inr         float64
 7   last_pymnt_amnt_inr       float64
 8   out_prncp_inr             float64
 9   out_prncp_inv_inr         float64
 10  collection_recovery_fee   float64
 11  collections_12mths_fee    float64
 12  mths_since_last_pymnt     int64
 13  num_accts_ever_120_pd     int64
 14  num_derog_rec             int64
 15  acc_now_delinq            int64
 16  chargeoff_within_12_mths  float64
 17  expected_loss_inr         float64
dtypes: float64(12), int64(5), object(1)
memory usage: 274.7+ MB

In [7]:
a.head()

,loan_id,loan_status,lgd_pct,total_pymnt_inr,total_pymnt_inv_inr,total_rec_prncp_inr,total_rec_int_inr,last_pymnt_amnt_inr,out_prncp_inr,out_prncp_inv_inr,collection_recovery_fee,collections_12mths_fee,mths_since_last_pymnt,num_accts_ever_120_pd,num_derog_rec,acc_now_delinq,chargeoff_within_12_mths,expected_loss_inr
0,LN000000001,0,0.0,102327.83,98339.43,80678.0,21649.83,13922.84,0.0,0.0,0.0,0.0,1,0,0,0,0.0,0.0
1,LN000000002,0,0.0,319635.13,309461.58,274166.0,45469.13,22957.63,0.0,0.0,0.0,0.0,1,0,1,0,0.0,0.0
2,LN000000003,0,0.0,79687.39,78661.62,59603.0,20084.39,NaN,0.0,0.0,0.0,0.0,1,0,0,0,0.0,0.0
3,LN000000004,0,0.0,509995.37,492937.00,246313.0,263682.37,13529.63,0.0,0.0,0.0,0.0,2,0,0,0,0.0,0.0
4,LN000000005,0,0.0,126155.61,126048.04,101471.0,24684.61,9962.35,0.0,0.0,0.0,0.0,2,0,0,0,0.0,0.0

In [8]:
#here we have merged all the datasets 
df = a.merge(b,on='loan_id',how='left').merge(c,on='loan_id',how='left').merge(d,on='loan_id',how='left').merge(e,on='loan_id',how='left').merge(f,on='loan_id',how='left').merge(g,on='loan_id',how='left').merge(h,on='loan_id',how='left').merge(i,on='loan_id',how='left')

In [9]:
#all of the columns from all 9 datasets are been merged here
df.head()

,loan_id,loan_status,lgd_pct,total_pymnt_inr,total_pymnt_inv_inr,total_rec_prncp_inr,total_rec_int_inr,last_pymnt_amnt_inr,out_prncp_inr,out_prncp_inv_inr,collection_recovery_fee,collections_12mths_fee,mths_since_last_pymnt,num_accts_ever_120_pd,num_derog_rec,acc_now_delinq,chargeoff_within_12_mths,expected_loss_inr,installment_due_inr,total_emi_due_inr,total_emi_paid_inr,emi_overdue_inr,emi_bounce_count,consecutive_missed_emis,last_emi_payment_date,emi_advance_paid_inr,prepayment_flag,avg_payment_delay_days,payment_mode,emi_bank_name,penal_charges_inr,waiver_granted_flag,waiver_amount_inr,loan_restructured_flag,ots_offered_flag,ots_accepted_flag,emi_coverage_ratio,pdc_count,emi_to_income_ratio,payment_discipline,issue_date,issue_year,issue_month,loan_amnt_inr,funded_amnt_inr,loan_term_months,int_rate_pct,installment_inr,annual_installment_inr,grade,sub_grade,loan_purpose,state_code,region,urban_index,application_type,pymnt_plan,hardship_flag,initial_list_status,disbursement_method,verification_status,rbi_repo_rate_pct,gdp_growth_pct,cpi_inflation_pct,rate_spread_pct,real_interest_rate_pct,dpd_bucket,npa_flag,risk_tier,cibil_score_band,recoveries_inr,recovery_fee_rate,policy_code,hardship_amount_inr,hardship_length_mths,net_loss_inr,provision_inr,has_collateral,collateral_type,collateral_value_inr,ltv_ratio_pct,loan_secured_flag,property_type,property_age_years,property_area_sqft,property_city_tier,vehicle_type,vehicle_age_years,insurance_flag,valuation_date,valuation_agency,charge_type,collateral_score,prop_value_inr,vehicle_value_inr,business_asset_val_inr,num_enquiries_30d,num_enquiries_90d,num_enquiries_6m,num_enquiries_12m,num_enquiries_24m,primary_enq_purpose,unique_lenders_enquired,rejected_applications,approved_applications,rejection_rate_pct,income_doc_type,kyc_status,field_verification_status,credit_committee_flag,loan_approved_date,processing_days,sourcing_channel,sourcing_agent_type,policy_deviation_flag,policy_override_flag,sanctioned_amount_inr,disbursed_amount_inr,tat_within_sla_flag,customer_id,age,gender,emp_title,emp_length_years,home_ownership,annual_inc_inr,dti_pct,cibil_score,earliest_cr_line,credit_hist_years,revol_bal_inr,revol_util_pct,open_acc,total_acc,mort_acc,pub_rec,delinq_2yrs,num_inq_last6m,num_inq_last12m,pct_tl_nvr_dlq,total_rev_hi_lim_inr,bc_util_pct,il_util_pct,all_util_pct,avg_cur_bal_inr,mths_since_last_delinq,mths_since_last_record,num_tl_op_past_12m,has_credit_card,num_credit_cards,total_cc_limit_inr,total_cc_balance_inr,cc_utilization_pct,cc_late_payments_count,cc_overlimit_count,cash_advance_inr,primary_card_type,primary_cc_bank,cc_spend_last3m_inr,avg_monthly_cc_spend_inr,top_spend_category,cc_payment_score,cc_default_risk_score,cc_emi_conversion_flag,branch_id,district_type,state_per_capita_inc_inr,state_literacy_rate_pct,state_agri_share_pct,state_industry_share_pct,state_services_share_pct,district_gdp_growth_pct,branch_age_years,branch_size,loan_officer_exp_years,branch_npa_rate,branch_sanction_rate,infrastructure_index,financial_inclusion_idx,credit_penetration_idx,covid_issue_year_flag,poor_monsoon_year_flag
0,LN000000001,0,0.0,102327.83,98339.43,80678.0,21649.83,13922.84,0.0,0.0,0.0,0.0,1,0,0,0,0.0,0.0,2793.17,100554.12,103925.57,0.00,0,0,Oct-2019,0.0,0,0.0,UPI,Union,0.00,0,0.0,0,0,0,3.99,6.0,0.2504,Excellent,Feb-2016,2016,2,80678.0,74992.0,36,14.91,2793.17,33518.0,C,C5,education,OR,East,0.33,Individual,N,N,w,DIRECT_PAY,Source Verified,6.25,8.2,4.5,8.66,10.41,Current,0,Medium Risk,Poor,0.0,0.0,1,0.00,0,0.0,397.93,0,NaN,0.0,NaN,0,NaN,0,0,NaN,NaN,0,0,May-2016,NaN,NaN,0.0,0.0,0.0,0.0,0,3,5,8,16,Personal Loan,3,0,8,0.0,NaN,Complete,Pending,0,Jan-2016,17.0,Branch,Online,0,0,74537.0,73139.0,0,CU01240276,45,M,Salaried,0.0,RENT,133866.0,14.99,624,Jun-1989,26.57,12242.63,27.8,11,27,0.0,0.0,0.0,5.0,7.0,65.4,763.84,25.9,75.9,43.1,1112.97,NaN,NaN,3,1,2,74592.0,39358.0,52.8,0,0,0.0,Basic,SBI,14230.0,4743.0,Online,100.0,0.2640,0,BR6893-OR,Urban,78000,72.9,28,30,42,7.25,26,Small,5.0,0.0536,0.769,18.1,0.700,0.540,0,1
1,LN000000002,0,0.0,319635.13,309461.58,274166.0,45469.13,22957.63,0.0,0.0,0.0,0.0,1,0,1,0,0.0,0.0,8465.45,304756.20,308223.00,0.00,1,0,May-2024,0.0,0,5.0,NACH,SBI,1488.08,0,0.0,0,0,0,8.95,6.0,0.1117,Good,May-2024,2024,5,274166.0,265041.0,36,7.00,8465.45,101585.0,A,A5,small_business,JH,East,0.36,Individual,N,N,w,CASH,Verified,6.50,6.8,4.9,0.50,2.10,Current,0,Low Risk,Excellent,0.0,0.0,1,11568.37,9,0.0,304.07,1,Business Assets,607261.0,45.15,1,NaN,0,0,NaN,NaN,0,1,Jul-2023,JLL,First Charge,72.0,0.0,0.0,607261.0,5,8,9,9,9,Personal Loan,1,1,8,11.1,Form16,Complete,Done,0,Oct-2024,4.0,Bancassurance,Bank Staff,1,0,266436.0,256842.0,1,CU01359733,40,M,Salaried,1.7,MORTGAGE,909588.0,6.73,840,Apr-2020,3.77,3124.69,24.4,17,21,4.0,0.0,1.0,1.0,4.0,81.8,67523.72,75.9,67.2,64.4,183.81,17.0,NaN,2,1,4,448024.0,97640.0,21.8,3,0,0.0,Basic,SBI,122785.0,40928.0,Retail,85.0,0.1715,0,BR4150-JH,Semi-Urban,72000,66.4,26,32,42,6.94,12,Small,6.2,0.0764,0.712,29.1,0.740,0.651,0,1
2,LN000000003,0,0.0,79687.39,78661.62,59603.0,20084.39,NaN,0.0,0.0,0.0,0.0,1,0,0,0,0.0,0.0,1366.55,81993.00,83657.21,0.00,1,0,Sep-2022,0.0,0,0.0,UPI,SBI,932.45,0,0.0,0,0,0,8.54,3.0,0.1171,Good,Dec-2021,2021,12,59603.0,54423.0,60,13.34,1366.55,16399.0,D,D5,home_improvement,TN,South,0.72,Individual,N,N,w,DIRECT_PAY,Source Verified,4.00,8.7,5.1,9.34,8.24,Current,0,Medium Risk,Poor,0.0,0.0,1,0.00,0,0.0,483.40,1,Property,4194101.0,1.42,1,Residential,20,3094,Tier1,NaN,0,0,Oct-2021,Cushman,Equitable Mortgage,48.1,4194101.0,0.0,0.0,1,2,6,12,21,Personal Loan,4,1,11,8.3,Salary Slip,Complete,Done,0,Feb-2021,12.0,Branch,DSA Partner,0,0,59049.0,57544.0,0,CU01350772,35,M,Salaried,11.3,OWN,140046.0,24.65,642,May-2017,3.66,28195.88,27.4,26,28,0.0,1.0,1.0,0.0,4.0,84.5,16570.17,38.7,40.0,28.3,1084.46,3.0,169.0,3,1,2,75123.0,44687.0,59.5,0,0,NaN,Silver,Axis,17153.0,5718.0,Fuel,NaN,0.2975,0,BR4542-TN,Semi-Urban,220000,80.1,10,34,56,7.02,21,Large,10.9,0.0181,0.575,54.5,0.825,0.598,0,0
3,LN000000004,0,0.0,509995.37,492937.00,246313.0,263682.37,13529.63,0.0,0.0,0.0,0.0,2,0,0,0,0.0,0.0,6088.88,511465.92,496707.66,14758.26,1,0,Jan-2023,0.0,0,0.0,Net Banking,ICICI,807.41,0,0.0,0,0,0,3.64,2.0,0.2750,Good,Nov-2020,2020,11,246313.0,224181.0,84,24.07,6088.88,73067.0,G,G5,home_improvement,RJ,North,0.45,Joint App,N,N,w,DIRECT_PAY,Source Verified,4.00,-6.6,6.2,20.07,17.87,Current,0,High Risk,Excellent,0.0,0.0,1,0.00,0,0.0,4730.75,1,Property,3462228.0,NaN,1,Residential,26,4869,Tier2,NaN,0,1,Mar-2020,ICRA,First Charge,NaN,3462228.0,0.0,0.0,0,2,5,8,9,Business Loan,6,0,8,0.0,Form16,Complete,Done,1,Nov-2020,11.0,Branch,Online,1,0,227840.0,216791.0,0,CU00064269,44,M,Salaried,2.4,MORTGAGE,265704.0,33.48,826,Aug-2002,18.16,9919.00,77.8,4,18,0.0,0.0,3.0,0.0,0.0,89.4,66114.89,51.0,79.6,63.2,2479.75,15.0,NaN,7,0,0,0.0,0.0,0.0,0,0,0.0,NaN,NaN,0.0,0.0,NaN,0.0,0.0000,0,BR4994-RJ,Urban,100000,66.1,24,28,48,5.88,23,Medium,30.0,0.0353,0.862,23.0,0.675,0.584,1,1
4,LN000000005,0,0.0,126155.61,126048.04,101471.0,24684.61,9962.35,0.0,0.0,0.0,0.0,2,0,0,0,0.0,0.0,2082.81,124968.60,120842.83,4125.77,0,0,May-2017,0.0,0,0.0,Net Banking,ICICI,0.00,0,0.0,0,0,0,61.18,2.0,0.0163,Excellent,Jul-2013,2013,7,101471.0,95361.0,60,8.52,2082.81,24994.0,A,A5,vacation,DL,North,0.97,Individual,Y,N,w,CASH,Verified,7.75,6.4,10.9,0.77,-2.38,Current,0,Low Risk,Poor,0.0,0.0,1,0.00,0,0.0,379.61,0,NaN,0.0,NaN,0,NaN,0,0,NaN,NaN,0,0,Feb-2012,NaN,NaN,0.0,0.0,0.0,0.0,1,1,2,2,3,Vehicle Loan,2,0,2,0.0,NaN,Complete,Done,0,Sep-2013,7.0,DSA,DSA Partner,0,0,99065.0,92233.0,1,CU01193840,64,F,Retired,4.7,RENT,1529175.0,18.06,635,Mar-1985,29.18,11015.36,70.7,25,42,0.0,2.0,6.0,1.0,3.0,88.4,8649.19,NaN,39.1,19.4,440.61,13.0,15.0,2,1,1,749805.0,369674.0,49.3,2,0,0.0,Silver,ICICI,186364.0,62121.0,Fuel,90.0,0.2882,0,BR2488-DL,Urban,390000,86.3,1,18,81,8.61,22,Medium,3.9,0.0281,0.805,92.3,0.651,0.549,0,1

In [10]:
#shape indicates rows and columns
df.shape

(2000000, 182)

In [11]:
before = df.memory_usage(deep=True).sum() / 1024**2
print(f"Memory Before Downcasting: {before:.2f} MB")

Memory Before Downcasting: 6608.61 MB

In [12]:
#here we have downcast the dtypes according to requirments 
for col in df.select_dtypes(include=['int']).columns:
    df[col] = pd.to_numeric(df[col], downcast='integer')

for col in df.select_dtypes(include=['float']).columns:
    df[col] = pd.to_numeric(df[col], downcast='float')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Columns: 182 entries, loan_id to poor_monsoon_year_flag
dtypes: float32(55), float64(29), int16(3), int32(1), int8(49), object(45)
memory usage: 1.6+ GB

In [14]:
after = df.memory_usage(deep=True).sum() / 1024**2

print(f"Memory After Downcasting: {after:.2f} MB")
print(f"Saved: {before-after:.2f} MB")
print(f"Reduction: {((before-after)/before)*100:.2f}%")

Memory After Downcasting: 5492.81 MB
Saved: 1115.80 MB
Reduction: 16.88%

In [15]:
#here we have have converted to parquet file which means we are compressing the file size
df.to_parquet("edaFinal.parquet",index=False)

In [16]:
df = pd.read_parquet("edaFinal.parquet")

In [17]:
print(f"Parquet DF Memory: {df.memory_usage(deep=True).sum()/1024**2:.2f} MB")

Parquet DF Memory: 5406.16 MB

In [18]:
df.head()

,loan_id,loan_status,lgd_pct,total_pymnt_inr,total_pymnt_inv_inr,total_rec_prncp_inr,total_rec_int_inr,last_pymnt_amnt_inr,out_prncp_inr,out_prncp_inv_inr,collection_recovery_fee,collections_12mths_fee,mths_since_last_pymnt,num_accts_ever_120_pd,num_derog_rec,acc_now_delinq,chargeoff_within_12_mths,expected_loss_inr,installment_due_inr,total_emi_due_inr,total_emi_paid_inr,emi_overdue_inr,emi_bounce_count,consecutive_missed_emis,last_emi_payment_date,emi_advance_paid_inr,prepayment_flag,avg_payment_delay_days,payment_mode,emi_bank_name,penal_charges_inr,waiver_granted_flag,waiver_amount_inr,loan_restructured_flag,ots_offered_flag,ots_accepted_flag,emi_coverage_ratio,pdc_count,emi_to_income_ratio,payment_discipline,issue_date,issue_year,issue_month,loan_amnt_inr,funded_amnt_inr,loan_term_months,int_rate_pct,installment_inr,annual_installment_inr,grade,sub_grade,loan_purpose,state_code,region,urban_index,application_type,pymnt_plan,hardship_flag,initial_list_status,disbursement_method,verification_status,rbi_repo_rate_pct,gdp_growth_pct,cpi_inflation_pct,rate_spread_pct,real_interest_rate_pct,dpd_bucket,npa_flag,risk_tier,cibil_score_band,recoveries_inr,recovery_fee_rate,policy_code,hardship_amount_inr,hardship_length_mths,net_loss_inr,provision_inr,has_collateral,collateral_type,collateral_value_inr,ltv_ratio_pct,loan_secured_flag,property_type,property_age_years,property_area_sqft,property_city_tier,vehicle_type,vehicle_age_years,insurance_flag,valuation_date,valuation_agency,charge_type,collateral_score,prop_value_inr,vehicle_value_inr,business_asset_val_inr,num_enquiries_30d,num_enquiries_90d,num_enquiries_6m,num_enquiries_12m,num_enquiries_24m,primary_enq_purpose,unique_lenders_enquired,rejected_applications,approved_applications,rejection_rate_pct,income_doc_type,kyc_status,field_verification_status,credit_committee_flag,loan_approved_date,processing_days,sourcing_channel,sourcing_agent_type,policy_deviation_flag,policy_override_flag,sanctioned_amount_inr,disbursed_amount_inr,tat_within_sla_flag,customer_id,age,gender,emp_title,emp_length_years,home_ownership,annual_inc_inr,dti_pct,cibil_score,earliest_cr_line,credit_hist_years,revol_bal_inr,revol_util_pct,open_acc,total_acc,mort_acc,pub_rec,delinq_2yrs,num_inq_last6m,num_inq_last12m,pct_tl_nvr_dlq,total_rev_hi_lim_inr,bc_util_pct,il_util_pct,all_util_pct,avg_cur_bal_inr,mths_since_last_delinq,mths_since_last_record,num_tl_op_past_12m,has_credit_card,num_credit_cards,total_cc_limit_inr,total_cc_balance_inr,cc_utilization_pct,cc_late_payments_count,cc_overlimit_count,cash_advance_inr,primary_card_type,primary_cc_bank,cc_spend_last3m_inr,avg_monthly_cc_spend_inr,top_spend_category,cc_payment_score,cc_default_risk_score,cc_emi_conversion_flag,branch_id,district_type,state_per_capita_inc_inr,state_literacy_rate_pct,state_agri_share_pct,state_industry_share_pct,state_services_share_pct,district_gdp_growth_pct,branch_age_years,branch_size,loan_officer_exp_years,branch_npa_rate,branch_sanction_rate,infrastructure_index,financial_inclusion_idx,credit_penetration_idx,covid_issue_year_flag,poor_monsoon_year_flag
0,LN000000001,0,0.0,102327.83,98339.43,80678.0,21649.83,13922.84,0.0,0.0,0.0,0.0,1,0,0,0,0.0,0.0,2793.17,100554.12,103925.57,0.00,0,0,Oct-2019,0.0,0,0.0,UPI,Union,0.00,0,0.0,0,0,0,3.99,6.0,0.2504,Excellent,Feb-2016,2016,2,80678.0,74992.0,36,14.91,2793.17,33518.0,C,C5,education,OR,East,0.33,Individual,N,N,w,DIRECT_PAY,Source Verified,6.25,8.2,4.5,8.66,10.410000,Current,0,Medium Risk,Poor,0.0,0.0,1,0.00,0,0.0,397.93,0,None,0.0,NaN,0,None,0,0,None,None,0,0,May-2016,None,None,0.000000,0.0,0.0,0.0,0,3,5,8,16,Personal Loan,3,0,8,0.0,None,Complete,Pending,0,Jan-2016,17.0,Branch,Online,0,0,74537.0,73139.0,0,CU01240276,45,M,Salaried,0.0,RENT,133866.0,14.990000,624,Jun-1989,26.57,12242.63,27.799999,11,27,0.0,0.0,0.0,5.0,7.0,65.400002,763.84,25.900000,75.900002,43.099998,1112.97,NaN,NaN,3,1,2,74592.0,39358.0,52.799999,0,0,0.0,Basic,SBI,14230.0,4743.0,Online,100.0,0.2640,0,BR6893-OR,Urban,78000,72.900002,28,30,42,7.25,26,Small,5.0,0.0536,0.769,18.100000,0.700,0.540,0,1
1,LN000000002,0,0.0,319635.13,309461.58,274166.0,45469.13,22957.63,0.0,0.0,0.0,0.0,1,0,1,0,0.0,0.0,8465.45,304756.20,308223.00,0.00,1,0,May-2024,0.0,0,5.0,NACH,SBI,1488.08,0,0.0,0,0,0,8.95,6.0,0.1117,Good,May-2024,2024,5,274166.0,265041.0,36,7.00,8465.45,101585.0,A,A5,small_business,JH,East,0.36,Individual,N,N,w,CASH,Verified,6.50,6.8,4.9,0.50,2.100000,Current,0,Low Risk,Excellent,0.0,0.0,1,11568.37,9,0.0,304.07,1,Business Assets,607261.0,45.150002,1,None,0,0,None,None,0,1,Jul-2023,JLL,First Charge,72.000000,0.0,0.0,607261.0,5,8,9,9,9,Personal Loan,1,1,8,11.1,Form16,Complete,Done,0,Oct-2024,4.0,Bancassurance,Bank Staff,1,0,266436.0,256842.0,1,CU01359733,40,M,Salaried,1.7,MORTGAGE,909588.0,6.730000,840,Apr-2020,3.77,3124.69,24.400000,17,21,4.0,0.0,1.0,1.0,4.0,81.800003,67523.72,75.900002,67.199997,64.400002,183.81,17.0,NaN,2,1,4,448024.0,97640.0,21.799999,3,0,0.0,Basic,SBI,122785.0,40928.0,Retail,85.0,0.1715,0,BR4150-JH,Semi-Urban,72000,66.400002,26,32,42,6.94,12,Small,6.2,0.0764,0.712,29.100000,0.740,0.651,0,1
2,LN000000003,0,0.0,79687.39,78661.62,59603.0,20084.39,NaN,0.0,0.0,0.0,0.0,1,0,0,0,0.0,0.0,1366.55,81993.00,83657.21,0.00,1,0,Sep-2022,0.0,0,0.0,UPI,SBI,932.45,0,0.0,0,0,0,8.54,3.0,0.1171,Good,Dec-2021,2021,12,59603.0,54423.0,60,13.34,1366.55,16399.0,D,D5,home_improvement,TN,South,0.72,Individual,N,N,w,DIRECT_PAY,Source Verified,4.00,8.7,5.1,9.34,8.240000,Current,0,Medium Risk,Poor,0.0,0.0,1,0.00,0,0.0,483.40,1,Property,4194101.0,1.420000,1,Residential,20,3094,Tier1,None,0,0,Oct-2021,Cushman,Equitable Mortgage,48.099998,4194101.0,0.0,0.0,1,2,6,12,21,Personal Loan,4,1,11,8.3,Salary Slip,Complete,Done,0,Feb-2021,12.0,Branch,DSA Partner,0,0,59049.0,57544.0,0,CU01350772,35,M,Salaried,11.3,OWN,140046.0,24.650000,642,May-2017,3.66,28195.88,27.400000,26,28,0.0,1.0,1.0,0.0,4.0,84.500000,16570.17,38.700001,40.000000,28.299999,1084.46,3.0,169.0,3,1,2,75123.0,44687.0,59.500000,0,0,NaN,Silver,Axis,17153.0,5718.0,Fuel,NaN,0.2975,0,BR4542-TN,Semi-Urban,220000,80.099998,10,34,56,7.02,21,Large,10.9,0.0181,0.575,54.500000,0.825,0.598,0,0
3,LN000000004,0,0.0,509995.37,492937.00,246313.0,263682.37,13529.63,0.0,0.0,0.0,0.0,2,0,0,0,0.0,0.0,6088.88,511465.92,496707.66,14758.26,1,0,Jan-2023,0.0,0,0.0,Net Banking,ICICI,807.41,0,0.0,0,0,0,3.64,2.0,0.2750,Good,Nov-2020,2020,11,246313.0,224181.0,84,24.07,6088.88,73067.0,G,G5,home_improvement,RJ,North,0.45,Joint App,N,N,w,DIRECT_PAY,Source Verified,4.00,-6.6,6.2,20.07,17.870001,Current,0,High Risk,Excellent,0.0,0.0,1,0.00,0,0.0,4730.75,1,Property,3462228.0,NaN,1,Residential,26,4869,Tier2,None,0,1,Mar-2020,ICRA,First Charge,NaN,3462228.0,0.0,0.0,0,2,5,8,9,Business Loan,6,0,8,0.0,Form16,Complete,Done,1,Nov-2020,11.0,Branch,Online,1,0,227840.0,216791.0,0,CU00064269,44,M,Salaried,2.4,MORTGAGE,265704.0,33.480000,826,Aug-2002,18.16,9919.00,77.800003,4,18,0.0,0.0,3.0,0.0,0.0,89.400002,66114.89,51.000000,79.599998,63.200001,2479.75,15.0,NaN,7,0,0,0.0,0.0,0.000000,0,0,0.0,None,None,0.0,0.0,None,0.0,0.0000,0,BR4994-RJ,Urban,100000,66.099998,24,28,48,5.88,23,Medium,30.0,0.0353,0.862,23.000000,0.675,0.584,1,1
4,LN000000005,0,0.0,126155.61,126048.04,101471.0,24684.61,9962.35,0.0,0.0,0.0,0.0,2,0,0,0,0.0,0.0,2082.81,124968.60,120842.83,4125.77,0,0,May-2017,0.0,0,0.0,Net Banking,ICICI,0.00,0,0.0,0,0,0,61.18,2.0,0.0163,Excellent,Jul-2013,2013,7,101471.0,95361.0,60,8.52,2082.81,24994.0,A,A5,vacation,DL,North,0.97,Individual,Y,N,w,CASH,Verified,7.75,6.4,10.9,0.77,-2.380000,Current,0,Low Risk,Poor,0.0,0.0,1,0.00,0,0.0,379.61,0,None,0.0,NaN,0,None,0,0,None,None,0,0,Feb-2012,None,None,0.000000,0.0,0.0,0.0,1,1,2,2,3,Vehicle Loan,2,0,2,0.0,None,Complete,Done,0,Sep-2013,7.0,DSA,DSA Partner,0,0,99065.0,92233.0,1,CU01193840,64,F,Retired,4.7,RENT,1529175.0,18.059999,635,Mar-1985,29.18,11015.36,70.699997,25,42,0.0,2.0,6.0,1.0,3.0,88.400002,8649.19,NaN,39.099998,19.400000,440.61,13.0,15.0,2,1,1,749805.0,369674.0,49.299999,2,0,0.0,Silver,ICICI,186364.0,62121.0,Fuel,90.0,0.2882,0,BR2488-DL,Urban,390000,86.300003,1,18,81,8.61,22,Medium,3.9,0.0281,0.805,92.300003,0.651,0.549,0,1

In [19]:
#Identify dirty records: int_rate_pct<0, annual_inc_inr==0, dti_pct>100, revol_util_pct<0. Create a dirty_flag binary column. Do NOT delete these rows — flag and impute.

df['dirty_flag'] = np.where(
    (
        (df['int_rate_pct'] < 0) |
        (df['annual_inc_inr'] == 0) |
        (df['dti_pct'] > 100) |
        (df['revol_util_pct'] < 0)
    ),
    1,
    0
)

In [20]:
print("Negative Interest:", (df['int_rate_pct'] < 0).sum())

print("Zero Income:", (df['annual_inc_inr'] == 0).sum())

print("DTI >100:", (df['dti_pct'] > 100).sum())

print("Negative Revol Util:",
      (df['revol_util_pct'] < 0).sum())

Negative Interest: 0
Zero Income: 0
DTI >100: 0
Negative Revol Util: 0

In [21]:
'''
MCAR (Missing Completely At Random) : missing has nothing to do with any variable in the dataset.
MAR (Missing At Random):Missingness depends on other observed variables, but not on the missing value itself.
MNAR (Missing Not At Random):Missingness depends on the value itself.
'''

'\nMCAR (Missing Completely At Random)\nMAR (Missing At Random)\nMNAR (Missing Not At Random)\n'

In [22]:
#here we figured out houmuch missing walues are been present in the df
missing_cols = [
    'mths_since_last_delinq',
    'mort_acc',
    'emp_length_years',
    'il_util_pct'
]

df[missing_cols].isnull().sum()

mths_since_last_delinq    1098640
mort_acc                   260330
emp_length_years           180539
il_util_pct                200167
dtype: int64

In [23]:
#here we converted it in terms of percentage
(df[missing_cols].isnull().sum() / len(df))*100

mths_since_last_delinq    54.93200
mort_acc                  13.01650
emp_length_years           9.02695
il_util_pct               10.00835
dtype: float64

In [50]:
df.columns

Index(['loan_id', 'loan_status', 'lgd_pct', 'total_pymnt_inr',
       'total_pymnt_inv_inr', 'total_rec_prncp_inr', 'total_rec_int_inr',
       'last_pymnt_amnt_inr', 'out_prncp_inr', 'out_prncp_inv_inr',
       ...
       'branch_size', 'loan_officer_exp_years', 'branch_npa_rate',
       'branch_sanction_rate', 'infrastructure_index',
       'financial_inclusion_idx', 'credit_penetration_idx',
       'covid_issue_year_flag', 'poor_monsoon_year_flag', 'dirty_flag'],
      dtype='object', length=183)

In [54]:
df.head()

,loan_id,loan_status,lgd_pct,total_pymnt_inr,total_pymnt_inv_inr,total_rec_prncp_inr,total_rec_int_inr,last_pymnt_amnt_inr,out_prncp_inr,out_prncp_inv_inr,collection_recovery_fee,collections_12mths_fee,mths_since_last_pymnt,num_accts_ever_120_pd,num_derog_rec,acc_now_delinq,chargeoff_within_12_mths,expected_loss_inr,installment_due_inr,total_emi_due_inr,total_emi_paid_inr,emi_overdue_inr,emi_bounce_count,consecutive_missed_emis,last_emi_payment_date,emi_advance_paid_inr,prepayment_flag,avg_payment_delay_days,payment_mode,emi_bank_name,penal_charges_inr,waiver_granted_flag,waiver_amount_inr,loan_restructured_flag,ots_offered_flag,ots_accepted_flag,emi_coverage_ratio,pdc_count,emi_to_income_ratio,payment_discipline,issue_date,issue_year,issue_month,loan_amnt_inr,funded_amnt_inr,loan_term_months,int_rate_pct,installment_inr,annual_installment_inr,grade,sub_grade,loan_purpose,state_code,region,urban_index,application_type,pymnt_plan,hardship_flag,initial_list_status,disbursement_method,verification_status,rbi_repo_rate_pct,gdp_growth_pct,cpi_inflation_pct,rate_spread_pct,real_interest_rate_pct,dpd_bucket,npa_flag,risk_tier,cibil_score_band,recoveries_inr,recovery_fee_rate,policy_code,hardship_amount_inr,hardship_length_mths,net_loss_inr,provision_inr,has_collateral,collateral_type,collateral_value_inr,ltv_ratio_pct,loan_secured_flag,property_type,property_age_years,property_area_sqft,property_city_tier,vehicle_type,vehicle_age_years,insurance_flag,valuation_date,valuation_agency,charge_type,collateral_score,prop_value_inr,vehicle_value_inr,business_asset_val_inr,num_enquiries_30d,num_enquiries_90d,num_enquiries_6m,num_enquiries_12m,num_enquiries_24m,primary_enq_purpose,unique_lenders_enquired,rejected_applications,approved_applications,rejection_rate_pct,income_doc_type,kyc_status,field_verification_status,credit_committee_flag,loan_approved_date,processing_days,sourcing_channel,sourcing_agent_type,policy_deviation_flag,policy_override_flag,sanctioned_amount_inr,disbursed_amount_inr,tat_within_sla_flag,customer_id,age,gender,emp_title,emp_length_years,home_ownership,annual_inc_inr,dti_pct,cibil_score,earliest_cr_line,credit_hist_years,revol_bal_inr,revol_util_pct,open_acc,total_acc,mort_acc,pub_rec,delinq_2yrs,num_inq_last6m,num_inq_last12m,pct_tl_nvr_dlq,total_rev_hi_lim_inr,bc_util_pct,il_util_pct,all_util_pct,avg_cur_bal_inr,mths_since_last_delinq,mths_since_last_record,num_tl_op_past_12m,has_credit_card,num_credit_cards,total_cc_limit_inr,total_cc_balance_inr,cc_utilization_pct,cc_late_payments_count,cc_overlimit_count,cash_advance_inr,primary_card_type,primary_cc_bank,cc_spend_last3m_inr,avg_monthly_cc_spend_inr,top_spend_category,cc_payment_score,cc_default_risk_score,cc_emi_conversion_flag,branch_id,district_type,state_per_capita_inc_inr,state_literacy_rate_pct,state_agri_share_pct,state_industry_share_pct,state_services_share_pct,district_gdp_growth_pct,branch_age_years,branch_size,loan_officer_exp_years,branch_npa_rate,branch_sanction_rate,infrastructure_index,financial_inclusion_idx,credit_penetration_idx,covid_issue_year_flag,poor_monsoon_year_flag,dirty_flag
0,LN000000001,0,0.0,102327.83,98339.43,80678.0,21649.83,13922.84,0.0,0.0,0.0,0.0,1,0,0,0,0.0,0.0,2793.17,100554.12,103925.57,0.00,0,0,Oct-2019,0.0,0,0.0,UPI,Union,0.00,0,0.0,0,0,0,3.99,6.0,0.2504,Excellent,Feb-2016,2016,2,80678.0,74992.0,36,14.91,2793.17,33518.0,C,C5,education,OR,East,0.33,Individual,N,N,w,DIRECT_PAY,Source Verified,6.25,8.2,4.5,8.66,10.410000,Current,0,Medium Risk,Poor,0.0,0.0,1,0.00,0,0.0,397.93,0,None,0.0,NaN,0,None,0,0,None,None,0,0,May-2016,None,None,0.000000,0.0,0.0,0.0,0,3,5,8,16,Personal Loan,3,0,8,0.0,None,Complete,Pending,0,Jan-2016,17.0,Branch,Online,0,0,74537.0,73139.0,0,CU01240276,45,M,Salaried,0.0,RENT,133866.0,14.990000,624,Jun-1989,26.57,12242.63,27.799999,11,27,0.0,0.0,0.0,5.0,7.0,65.400002,763.84,25.900000,75.900002,43.099998,1112.97,NaN,NaN,3,1,2,74592.0,39358.0,52.799999,0,0,0.0,Basic,SBI,14230.0,4743.0,Online,100.0,0.2640,0,BR6893-OR,Urban,78000,72.900002,28,30,42,7.25,26,Small,5.0,0.0536,0.769,18.100000,0.700,0.540,0,1,0
1,LN000000002,0,0.0,319635.13,309461.58,274166.0,45469.13,22957.63,0.0,0.0,0.0,0.0,1,0,1,0,0.0,0.0,8465.45,304756.20,308223.00,0.00,1,0,May-2024,0.0,0,5.0,NACH,SBI,1488.08,0,0.0,0,0,0,8.95,6.0,0.1117,Good,May-2024,2024,5,274166.0,265041.0,36,7.00,8465.45,101585.0,A,A5,small_business,JH,East,0.36,Individual,N,N,w,CASH,Verified,6.50,6.8,4.9,0.50,2.100000,Current,0,Low Risk,Excellent,0.0,0.0,1,11568.37,9,0.0,304.07,1,Business Assets,607261.0,45.150002,1,None,0,0,None,None,0,1,Jul-2023,JLL,First Charge,72.000000,0.0,0.0,607261.0,5,8,9,9,9,Personal Loan,1,1,8,11.1,Form16,Complete,Done,0,Oct-2024,4.0,Bancassurance,Bank Staff,1,0,266436.0,256842.0,1,CU01359733,40,M,Salaried,1.7,MORTGAGE,909588.0,6.730000,840,Apr-2020,3.77,3124.69,24.400000,17,21,4.0,0.0,1.0,1.0,4.0,81.800003,67523.72,75.900002,67.199997,64.400002,183.81,17.0,NaN,2,1,4,448024.0,97640.0,21.799999,3,0,0.0,Basic,SBI,122785.0,40928.0,Retail,85.0,0.1715,0,BR4150-JH,Semi-Urban,72000,66.400002,26,32,42,6.94,12,Small,6.2,0.0764,0.712,29.100000,0.740,0.651,0,1,0
2,LN000000003,0,0.0,79687.39,78661.62,59603.0,20084.39,NaN,0.0,0.0,0.0,0.0,1,0,0,0,0.0,0.0,1366.55,81993.00,83657.21,0.00,1,0,Sep-2022,0.0,0,0.0,UPI,SBI,932.45,0,0.0,0,0,0,8.54,3.0,0.1171,Good,Dec-2021,2021,12,59603.0,54423.0,60,13.34,1366.55,16399.0,D,D5,home_improvement,TN,South,0.72,Individual,N,N,w,DIRECT_PAY,Source Verified,4.00,8.7,5.1,9.34,8.240000,Current,0,Medium Risk,Poor,0.0,0.0,1,0.00,0,0.0,483.40,1,Property,4194101.0,1.420000,1,Residential,20,3094,Tier1,None,0,0,Oct-2021,Cushman,Equitable Mortgage,48.099998,4194101.0,0.0,0.0,1,2,6,12,21,Personal Loan,4,1,11,8.3,Salary Slip,Complete,Done,0,Feb-2021,12.0,Branch,DSA Partner,0,0,59049.0,57544.0,0,CU01350772,35,M,Salaried,11.3,OWN,140046.0,24.650000,642,May-2017,3.66,28195.88,27.400000,26,28,0.0,1.0,1.0,0.0,4.0,84.500000,16570.17,38.700001,40.000000,28.299999,1084.46,3.0,169.0,3,1,2,75123.0,44687.0,59.500000,0,0,NaN,Silver,Axis,17153.0,5718.0,Fuel,NaN,0.2975,0,BR4542-TN,Semi-Urban,220000,80.099998,10,34,56,7.02,21,Large,10.9,0.0181,0.575,54.500000,0.825,0.598,0,0,0
3,LN000000004,0,0.0,509995.37,492937.00,246313.0,263682.37,13529.63,0.0,0.0,0.0,0.0,2,0,0,0,0.0,0.0,6088.88,511465.92,496707.66,14758.26,1,0,Jan-2023,0.0,0,0.0,Net Banking,ICICI,807.41,0,0.0,0,0,0,3.64,2.0,0.2750,Good,Nov-2020,2020,11,246313.0,224181.0,84,24.07,6088.88,73067.0,G,G5,home_improvement,RJ,North,0.45,Joint App,N,N,w,DIRECT_PAY,Source Verified,4.00,-6.6,6.2,20.07,17.870001,Current,0,High Risk,Excellent,0.0,0.0,1,0.00,0,0.0,4730.75,1,Property,3462228.0,NaN,1,Residential,26,4869,Tier2,None,0,1,Mar-2020,ICRA,First Charge,NaN,3462228.0,0.0,0.0,0,2,5,8,9,Business Loan,6,0,8,0.0,Form16,Complete,Done,1,Nov-2020,11.0,Branch,Online,1,0,227840.0,216791.0,0,CU00064269,44,M,Salaried,2.4,MORTGAGE,265704.0,33.480000,826,Aug-2002,18.16,9919.00,77.800003,4,18,0.0,0.0,3.0,0.0,0.0,89.400002,66114.89,51.000000,79.599998,63.200001,2479.75,15.0,NaN,7,0,0,0.0,0.0,0.000000,0,0,0.0,None,None,0.0,0.0,None,0.0,0.0000,0,BR4994-RJ,Urban,100000,66.099998,24,28,48,5.88,23,Medium,30.0,0.0353,0.862,23.000000,0.675,0.584,1,1,0
4,LN000000005,0,0.0,126155.61,126048.04,101471.0,24684.61,9962.35,0.0,0.0,0.0,0.0,2,0,0,0,0.0,0.0,2082.81,124968.60,120842.83,4125.77,0,0,May-2017,0.0,0,0.0,Net Banking,ICICI,0.00,0,0.0,0,0,0,61.18,2.0,0.0163,Excellent,Jul-2013,2013,7,101471.0,95361.0,60,8.52,2082.81,24994.0,A,A5,vacation,DL,North,0.97,Individual,Y,N,w,CASH,Verified,7.75,6.4,10.9,0.77,-2.380000,Current,0,Low Risk,Poor,0.0,0.0,1,0.00,0,0.0,379.61,0,None,0.0,NaN,0,None,0,0,None,None,0,0,Feb-2012,None,None,0.000000,0.0,0.0,0.0,1,1,2,2,3,Vehicle Loan,2,0,2,0.0,None,Complete,Done,0,Sep-2013,7.0,DSA,DSA Partner,0,0,99065.0,92233.0,1,CU01193840,64,F,Retired,4.7,RENT,1529175.0,18.059999,635,Mar-1985,29.18,11015.36,70.699997,25,42,0.0,2.0,6.0,1.0,3.0,88.400002,8649.19,NaN,39.099998,19.400000,440.61,13.0,15.0,2,1,1,749805.0,369674.0,49.299999,2,0,0.0,Silver,ICICI,186364.0,62121.0,Fuel,90.0,0.2882,0,BR2488-DL,Urban,390000,86.300003,1,18,81,8.61,22,Medium,3.9,0.0281,0.805,92.300003,0.651,0.549,0,1,0

In [68]:
#here we checked wheather our column contains any of null values or not 

#Na,NaN,Null all of them are same

null_count = df.isnull().sum()
null_count = null_count[null_count > 0]
print(null_count)

last_pymnt_amnt_inr           119889
collection_recovery_fee       120086
avg_payment_delay_days        120364
emi_bank_name                 120236
pdc_count                     120057
cibil_score_band                  10
collateral_type              1258896
ltv_ratio_pct                1472196
property_type                1679672
property_city_tier           1679672
vehicle_type                 1879789
valuation_agency             1370048
charge_type                  1258896
collateral_score              298379
income_doc_type               308704
field_verification_status     119475
processing_days               119899
emp_length_years              180539
annual_inc_inr                 40066
revol_util_pct                140097
mort_acc                      260330
pub_rec                       118951
delinq_2yrs                   100207
num_inq_last6m                 80130
pct_tl_nvr_dlq                 59892
bc_util_pct                   160397
il_util_pct                   200167
all_util_pct                   79649
avg_cur_bal_inr               100027
mths_since_last_delinq       1098640
mths_since_last_record       1598332
cash_advance_inr              160223
primary_card_type             560528
primary_cc_bank               560528
top_spend_category            560528
cc_payment_score              160149
loan_officer_exp_years        139366
branch_sanction_rate          140557
dtype: int64

#d:find missing values and fill them